name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Default steps
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        run: |
          echo -e "\e[36m Build \e[0m" 
          yarn run build

      - name: Upload S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: dev-observe-website
          bucket-region: us-east-1
          delete-removed: true
