name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: dev.observe.space
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1' # optional: defaults to us-east-1
      SOURCE_DIR: './dist/' # optional: defaults to entire repository

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Default steps
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use Yarn
        run: |
          echo -e "\e[36m Use Yarn - Yarn version: \e[0m $(yarn --version)" 
          yarn

      - name: Build
        run: |
          echo -e "\e[36m Build \e[0m" 
          yarn run build

      - name: Upload S3
        run: aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }} --delete --region ${{ env.AWS_REGION }}
